### ISSUE TITLE
Pitanja

### ISSUE THREAD

**Issue by AmrSa2002** [AmrSa2002/APC_projekat-Parser_UDP_datagrama#1]
@eniokaljic
- da li i ulaz i izlaz trebaju da sadržavaju sve signale osim clk i rst kao što je u trenutnoj verziji prikaza signala u wavedromu.
- da li možemo zanemariti empty signal jer će uvijek biti jednak nuli odnosno da ga nikako ne prikazujemo?
- što se tiče izlaza u channel nama se traži vektor koji sadrži {IP adresu izvora, UDP port izvora, IP adresu odredišta, UDP port odredišta} što odgovara 12B, da li ćemo i ovaj signal prenositi po 1B pošto radimo sa 8-bit Avalon-ST interfejsom ili će sve ići u jednu magistralu od 12B ili će ići magistrala koja odgovara dužini UDP payloada?  Vektor traženih podataka će imati manje bita od UDP payloada koji ide paralelno sa njim pa hoćemo li ovaj vektor popunjavati nulama do vrijednosti dužine payloada?
- da li trebamo razmatrati različite testne scenarije pošto trenutno razmatramo idealni scenarij kada je ready signal uvijek aktivan?

**Comment by eniokaljic** [comment]
1. Da, _clk_ i _rst_ su odvojeni od ulaznog i izlaznog Avalon-ST interfejsa, tj. zajednički su za cijeli sklop.
2. Izbacite _empty,_ ne treba vam.
3. Neka to bude vektor širine 96 bita (12B), koji se prenosi nepromijenjen od prvog do posljednjeg transfera UDP _payload-a._
4. Razradite različite scenarije, npr.:
- dužina paketa je djeljiva sa 64B bez ostatka (bez _backpressure,_ tj. _ready_ = '1' svo vrijeme),
- dužina paketa nije djeljiva sa 64B bez ostatka (bez _backpressure,_ tj. _ready_ ='1' svo vrijeme),
- dužina paketa je djeljiva sa 64B bez ostatka (sa _backpressure,_ tj. _ready_ postane '0' u nekom trenutku, te se vrati na '1' nakon nekoliko takt intervala - više od 2 intervala),
- dužina paketa nije djeljiva sa 64B bez ostatka (sa _backpressure,_ tj. _ready_ postane '0' u nekom trenutku, te se vrati na '1' nakon nekoliko takt intervala - više od 2 intervala).

Opis signala morate razdvojiti na opis ulaznih i opis izlaznih signala, jer nemaju isto značenje (npr. _channel_ ne postoji na ulazu ali postoji na izlazu). Također, potkrala vam se greška u dijagramu - sve signale ste prikazali u jednoj grupi.
